language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov

script:
  - pytest
  - coverage run -m pytest -v tests && coverage report -m

after_success:
  - ./codecov
