[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "E-market data explorer"
authors = [{name = "Paul Yang", email = "paulyang0125@gmail.com"}]
dynamic = ["version", "description"]
